
services:
    postgres_in_lms_network:
        container_name: postgres_authors
        image: postgres:16
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: authors_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - "postgres_authors_volume:/var/lib/postgresql/data"
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s


networks:
    lms_network:
        external: true

volumes:
    postgres_authors_volume: